// Generated by Wrangler on Mon Jul 22 2024 21:14:52 GMT-0700 (Pacific Daylight Saving Time)
// by running `wrangler types`

interface Env {
	Users: KVNamespace;
	KEYSTATIC_GITHUB_CLIENT_ID: string;
	KEYSTATIC_GITHUB_CLIENT_SECRET: string;
	KEYSTATIC_SECRET: string;
	PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: string;
	PUBLIC_DOMAIN: string;
	SITE_URL: string;
	PUBLIC_SENTRY_DSN: string;
	SENTRY_AUTH_TOKEN: string;
	REPLYBOX_SECRET_KEY: string;
	PRIVATE_KEY: string;
	PUBLIC_KEY: string;
	SIGN_IN_TEMPLATE_ID: string;
	SENDGRID_REPLY_TO: string;
	SENDGRID_FROM_NAME: string;
	SENDGRID_FROM_EMAIL: string;
	SENDGRID_API_KEY: string;
}
