// Generated by Wrangler on Sat Aug 24 2024 12:38:13 GMT-0700 (Pacific Daylight Saving Time)
// by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	Users: KVNamespace;
	KEYSTATIC_GITHUB_CLIENT_ID: string;
	KEYSTATIC_GITHUB_CLIENT_SECRET: string;
	KEYSTATIC_SECRET: string;
	PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: string;
	PUBLIC_DOMAIN: string;
	SITE_URL: string;
	REPLYBOX_SECRET_KEY: string;
	PRIVATE_KEY: string;
	PUBLIC_KEY: string;
	SIGN_IN_TEMPLATE_ID: string;
	SENDGRID_REPLY_TO: string;
	SENDGRID_FROM_NAME: string;
	SENDGRID_FROM_EMAIL: string;
	SENDGRID_API_KEY: string;
	SENDGRID_LIST_ID: string;
}
